<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Promises, async/await 03-08 </title>

</head>
<body>
  <script>
  	"use strict";

  	// ==================================== Promises chaining ====================================

    // a call to promise.then returns a promise, so that we can call the next .then on it.

    // When a handler returns a value, it becomes the result of that promise, so the next .then is called with it.

    // ==================================== Error handling with promises ====================================

    // The code of a promise executor and promise handlers has an "invisible try..catch" around it. 
    // If an exception happens, it gets caught and treated as a rejection.
    // If an error was throwed inside a .then handler, that means a rejected promise as well.

    // ==================================== Promise API ====================================

    // If any of the promises is rejected, the promise returned by Promise.all immediately rejects with that error.

    // ==================================== Promisification ====================================

    // the conversion of a function that accepts a callback into a function that returns a promise.

    // ==================================== Microtasks ====================================

    // Promise handling is always asynchronous, as all promise actions pass through the internal “promise jobs” queue, also called “microtask queue” (ES8 term).


    // ==================================== Async/await ====================================

    // 'Async' keyword before a function:
    // means a function always returns a promise. Other values are wrapped in a resolved promise automatically.

    async function f() {
      return 1;
    }

    f().then(result => console.log(result)); // 1

    // Await: makes JavaScript wait until that promise settles and returns its result.
    async function f2() {

      let promise = new Promise((resolve, reject) => {
        setTimeout(() => resolve("done!"), 1000)
      });

      // works only inside async functions!
      // await literally suspends the function execution until the promise settle
      let result = await promise; 

      console.log(result); // "done!" after 1 sec
    }

    f2();

    // It’s just a more elegant syntax of getting the promise result than promise.then, easier to read and write.
    // await won’t work in the top-level code

    // syntax error in top-level code
    // ERROR!
    // let response = await fetch('/article/promise-chaining/user.json'); 
    // let user = await response.json();

    // a solution to this: wrap it into an anonymous async function
    // (async () => {
    //   let response = await fetch('/article/promise-chaining/user.json');
    //   let user = await response.json();
    //   // ...
    // })();

    // TASKs
    // Rewrite using async/await
    async function loadJson(url) {
        let response = await fetch(url);

        if (response.status == 200) {
          let json = await response.json();
          return json;
        } else {
          throw new Error(response.status);
        }
    }

    loadJson('https://no-such-user.json').catch(result => console.log(result));

    // Rewrite "rethrow" with async/await
    {    
      class HttpError extends Error {
          constructor(response) {
            super(`${response.status} for ${response.url}`);
            this.name = 'HttpError';
            this.response = response;
          }
        }

        async function loadJson(url) {
          let response = await fetch(url);

          if (response.status == 200) {
            return response.json();
          } else {
            throw new HttpError(response);
          }
        }

        // Ask for a user name until github returns a valid user
        async function demoGithubUser() {
          let user;

          while(true) {
            let name = prompt("Enter a name?", "iliakan");

            try {
              user = await loadJson(`https://api.github.com/users/${name}`);
              break; // just break if no error
            } catch(err) {
              if (err instanceof HttpError) {
                console.log("No such user, please reenter.");
                name = prompt("Enter a name?", "iliakan");
              } else {
                throw new Error("unknown error", err);
              }
            }
          }
          console.log(`Full name: ${user.name}.`);
          return user;
        }

        demoGithubUser();
    }

    // Call async from non-async
    async function wait() {
      await new Promise(resolve => setTimeout(resolve, 1000));

      return 10;
    }

    function f3() {
      // ...what to write here?
      // we need to call async wait() and wait to get 10
      // remember, we can't use "await"

      // fake an async ? NO
      (async () => {
        let result = await wait();
        console.log(result);
      })();

      // Correct answer: Just treat async call as promise and attach .then to it:
      wait().then(result => console.log("the cool " + result));
    }

    f3();

  </script>
</body>
</html>